version: '3.8'
services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    environment:
        POSTGRES_DB: keycloak-db
        POSTGRES_PASSWORD: root
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5431:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ems-app

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    command: ["start-dev", "--http-port=8180", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak-db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
    ports:
      - 8180:8180
    volumes:
      - ./imports/realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - ems-app
    depends_on:
    - postgres

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=eventManagementDb
    ports:
      - 27018:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
      - mongodb-config:/data/configdb
    networks:
      - ems-app

volumes:
  postgres_data:
    driver: local
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
  mongodb-config:
    driver: local

networks:
  ems-app:
    driver: bridge